### ISSUE TITLE
ImportError: No module named gdal

### ISSUE THREAD

**Issue by grl-sage** [GitHubRGI/geopackage-python#23]
Installed the following in the order below

python v2.7.11 from https://www.python.org/downloads/
gdal-111-1800-x64-core.msi
gdal-111-1800-x64-mrsid.msi
GDAL-1.11.3.win-amd64-py2.7.msi

Tried to tile up some data but got message below. 

Traceback (most recent call last):
  File "gdal2tiles_parallel.py", line 66, in <module>
    import gdal
ImportError: No module named gdal

**Comment by stevendlander** [comment]
This error occurs on Windows when you try to run the script in the CMD shell without the loaded GDAL extensions.  In the start menu, the GDAL folder has a special shell shortcut called `GDAL 111 (MSVC 2013 Win64) Command Prompt` or something similar.

Launch that command prompt and then try to run gdal2tiles_parallel.py and it should work.

**Comment by grl-sage** [comment]
Same Error using the GDAL shell.



________________________________

**Comment by grl-sage** [comment]
I noticed the environment variable set in the command window, but I do not have this directory.
PYTHONPATH=C:\Program Files\GDAL\python
________________________________

**Comment by grl-sage** [comment]
After removing some windows registry entry editing due to another python install that had remaining paths in the registry, I tried another install and get the message.

Traceback (most recent call last):
  File "gdal2tiles_parallel.py", line 2498, in <module>
    main(None)
  File "gdal2tiles_parallel.py", line 2450, in main
    gdal2tiles = GDAL2Tiles( argv[1:] ) # handle command line options
  File "gdal2tiles_parallel.py", line 704, in __init__
    self.optparse_init()
  File "gdal2tiles_parallel.py", line 815, in optparse_init
    p = OptionParser(usage, version="%prog "+ __version__)
NameError: global name '__version__' is not defined

This is without MrSid install.  With MrSid get additional error message.  I looked in windows explorer and the dll is there.

ERROR 1: Can't load requested DLL: C:\Program Files\GDAL\gdalplugins\gdal_MrSID.dll
126: The specified module could not be found.

ERROR 1: Can't load requested DLL: C:\Program Files\GDAL\gdalplugins\gdal_MrSID.dll
126: The specified module could not be found.

**Comment by stevendlander** [comment]
Looks like some refactoring work that was meant for a different branch was put into master instead.  I have reverted `gdal2tiles_parallel.py` to the previous version and tested, so it should be working now if you pull down the changes.  Would you mind trying that?

**Comment by grl-sage** [comment]
OK. I will look at it in the morning.

**Comment by stevendlander** [comment]
Marking this as closed.  Feel free to re-open if this is still an issue.
