### ISSUE TITLE
gdal2tiles_parallel.py: error: Processing of several input files is not supported

### ISSUE THREAD

**Issue by grl-sage** [GitHubRGI/geopackage-python#24]
Script below works fine but the tiles that are created are less resolution than the original input image. It makes folder 9-15. 

python Tiling\gdal2tiles_parallel.py -p geodetic -e -a 0,0,0 C:\GeoPackage\Suitable\Suitability.png C:\GeoPackage\Suitability\Tiles

I specified -z 16 to create 16 zoom levels.

python Tiling\gdal2tiles_parallel.py –z 16 -p geodetic -e -a 0,0,0 C:\GeoPackage\Suitable\Suitability.png C:\GeoPackage\Suitability\Tiles

I receive the error:

Usage: gdal2tiles_parallel.py [options] input_file(s) [output]

gdal2tiles_parallel.py: error: Processing of several input files is not supporte
d.

Please first use a tool like gdal_vrtmerge.py or gdal_merge.py on the files:
                gdal_vrtmerge.py -o merged.vrt z 16 C:\GeoPackage\Suitability\Suitability.png

**Comment by stevendlander** [comment]
* For your first concern re: tiles at less resolution than the input image: The script will automatically determine zoom level closest to the original raster native resolution and then warp the image to that new resolution that matches the tile level.
* You can specify the zoom levels you would like the script to make in one of two ways at runtime:
`-z 9-16` tells the script to make levels 9 through 16 inclusive, `-z 16` tells the script to *just* make level 16.  There should be nothing wrong with the command you posted telling the script to make zoom level 16, and I have verified that the same command works fine for my setup.  The error you are receiving about multiple input files suggests the script believes the second file path you gave it is another raster to tile which it clearly is not.  Try either adding a trailing slash to the path (`C:\GeoPackage\Suitability\Tiles\`) or alternatively you can tile all over again with the `-z 9-16` flag into a new directory.

**Comment by stevendlander** [comment]
Closing unless this is still an issue.
