### ISSUE TITLE
features2gpkg_parallel.py: New development

### ISSUE THREAD

**Issue by stevendlander** [GitHubRGI/geopackage-python#7]
Create a script that can accept certain OGR-supported vector files and creates a GeoPackage with from that data.

**Comment by techmavengeospatial** [comment]
Is that really needed since GDAL OGR already natively supports that.  Use OGR2OGR and convert any OGR Vector File or Database to a GeoPackage http://www.gdal.org/ogr2ogr.html 
You can process an entire folder of shapefiles or individual files
ogr2ogr -f GPKG %outputfolder%\name.gpkg %sourcefolder%

**Comment by stevendlander** [comment]
Probably not need any longer since OGR does indeed support this now.  Back in late 2014, I dont think the support was there.
